import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "@": fileURLToPath(new URL(".", import.meta.url)),
    },
  },
  test: {
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "json", "html"],
      // Generated artifacts are not coverable source: public/*.js bundles are
      // regenerated by `npm run prebuild` on every build and scripts/ is build
      // tooling. Excluding them keeps the floor measuring source, not bundle
      // churn.
      exclude: ["public/**", "scripts/**"],
      // Floors measured on origin/main 2026-09-25: 42.18% lines, 70.22%
      // functions on the included source (39.66% / 70.14% with generated
      // artifacts counted). Ratchet: raise `lines` by 2 points per week until
      // it reaches 65 — bump the value below on the weekly cadence.
      // Per-module target is 85% lines; modules under target are pinned at
      // their measured floor. Raise these as tests land — never lower them to
      // green a PR.
      thresholds: {
        lines: 42,
        functions: 70,
        "lib/auth/**": { lines: 47 },
        "lib/routing/**": { lines: 68 },
        "lib/security/**": { lines: 79 },
        "lib/wallet/**": { lines: 46 },
        "lib/vault/**": { lines: 66 },
        "lib/muse/**": { lines: 9 },
        "lib/decisions/**": { lines: 85 },
        "lib/approvals/**": { lines: 56 },
        "app/api/inbound/**": { lines: 29 },
        // Measured 0% — floor exists to catch regressions the day tests land,
        // but cannot ratchet below zero. Gap to 85% tracked in the PR.
        "app/api/muse/**": { lines: 0 },
        "app/api/wallet/**": { lines: 0 },
        "app/api/vault/**": { lines: 0 },
      },
    },
  },
});
