#!/usr/bin/env python3
"""C24: generate the platform-disable list from the pinned Hermes snapshot.

Enumerates every adapter from gateway.config.Platform, every directory under
plugins/platforms/, AND every name a plugin passes to ctx.register_platform()
— the registered name is the actual `platforms:` config key, and a plugin
directory is not required to match it — then appends a `platforms:` block to
the box config with `enabled: false` for each except api_server, the single
door the control plane owns (C12). Hand-maintained lists drift; upstream
adding an adapter (photon above all) must never silently open a second
channel into the agent, so the template build runs this script and FAILS if
it fails. `--verify` re-checks a finished config against the same union.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

NAME_RE = re.compile(r"^[a-z0-9_]+$")
# The pinned 0.20.x snapshot ships 20+ adapters between the enum and the
# plugin dirs. A smaller result means enumeration silently broke — fail.
MIN_EXPECTED = 15


def enum_platforms(repo: Path) -> set[str]:
    sys.path.insert(0, str(repo))
    try:
        from gateway.config import Platform  # type: ignore
    finally:
        sys.path.pop(0)
    return {member.value for member in Platform}


REGISTER_RE = re.compile(
    r"register_platform\(\s*(?:[a-z_]+\s*=\s*)?name\s*=\s*[\"']([^\"']+)[\"']"
)


def plugin_platforms(repo: Path) -> set[str]:
    root = repo / "plugins" / "platforms"
    if not root.is_dir():
        raise SystemExit(f"FATAL: {root} does not exist — snapshot layout changed?")
    names: set[str] = set()
    for entry in root.iterdir():
        if not entry.is_dir() or entry.name.startswith(("_", ".")):
            continue
        names.add(entry.name)
        # The config key is the name registered at runtime, not the directory:
        # a dir/key mismatch would make a dir-derived `enabled: false` inert.
        registered = {
            match
            for source in entry.rglob("*.py")
            for match in REGISTER_RE.findall(source.read_text(errors="replace"))
        }
        if not registered:
            raise SystemExit(
                f"FATAL: no register_platform(name=...) found under {entry} — "
                "cannot prove the config key; refusing to guess"
            )
        names |= registered
    return names


def all_platforms(repo: Path) -> set[str]:
    names = enum_platforms(repo) | plugin_platforms(repo)
    bad = sorted(name for name in names if not NAME_RE.match(name))
    if bad:
        raise SystemExit(f"FATAL: non-conforming platform names: {bad}")
    if "api_server" not in names:
        raise SystemExit("FATAL: api_server missing from the enumerated platforms")
    if len(names) < MIN_EXPECTED:
        raise SystemExit(
            f"FATAL: only {len(names)} platforms enumerated (< {MIN_EXPECTED}) — "
            "generation is broken, refusing to write a partial disable list"
        )
    return names


def verify(repo: Path, config: Path) -> None:
    import yaml

    cfg = yaml.safe_load(config.read_text()) or {}
    platforms = cfg.get("platforms") or {}
    enabled = sorted(
        name
        for name, block in platforms.items()
        if isinstance(block, dict) and block.get("enabled")
    )
    if enabled != ["api_server"]:
        raise SystemExit(
            f"FATAL (C24): enabled platforms must be exactly ['api_server'], got {enabled}"
        )
    missing = sorted(all_platforms(repo) - set(platforms))
    if missing:
        raise SystemExit(f"FATAL (C24): adapters missing from the disable list: {missing}")
    print(
        f"C24 gate ok: {len(platforms)} adapters, api_server only enabled",
        file=sys.stderr,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--hermes-repo", required=True, type=Path)
    parser.add_argument("--config", required=True, type=Path)
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()

    if args.verify:
        verify(args.hermes_repo, args.config)
        return

    names = all_platforms(args.hermes_repo)

    lines = ["", "# GENERATED by generate_platforms.py (C24) — do not hand-edit."]
    lines.append("platforms:")
    lines.append("  api_server:")
    lines.append("    enabled: true")
    for name in sorted(names - {"api_server"}):
        lines.append(f"  {name}: {{ enabled: false }}")
    lines.append("")

    config = args.config
    text = config.read_text() if config.exists() else ""
    if re.search(r"^platforms:", text, flags=re.M):
        raise SystemExit(
            f"FATAL: {config} already contains a platforms block — "
            "refusing to append a second one"
        )
    config.write_text(text.rstrip("\n") + "\n" + "\n".join(lines))
    print(
        f"platforms block generated: {len(names)} adapters, api_server only enabled",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
