#!/usr/bin/env python3
"""C24: generate the platform-disable list from the pinned Hermes snapshot.

Enumerates every adapter from gateway.config.Platform PLUS every directory
under plugins/platforms/ and appends a `platforms:` block to the box config
with `enabled: false` for each — except api_server, the single door the
control plane owns (C12). Hand-maintained lists drift; upstream adding an
adapter (photon above all) must never silently open a second channel into
the agent, so the template build runs this script and FAILS if it fails.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

NAME_RE = re.compile(r"^[a-z0-9_]+$")
# The pinned 0.20.x snapshot ships 20+ adapters between the enum and the
# plugin dirs. A smaller result means enumeration silently broke — fail.
MIN_EXPECTED = 15


def enum_platforms(repo: Path) -> set[str]:
    sys.path.insert(0, str(repo))
    try:
        from gateway.config import Platform  # type: ignore
    finally:
        sys.path.pop(0)
    return {member.value for member in Platform}


def plugin_platforms(repo: Path) -> set[str]:
    root = repo / "plugins" / "platforms"
    if not root.is_dir():
        raise SystemExit(f"FATAL: {root} does not exist — snapshot layout changed?")
    return {
        entry.name
        for entry in root.iterdir()
        if entry.is_dir() and not entry.name.startswith(("_", "."))
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--hermes-repo", required=True, type=Path)
    parser.add_argument("--config", required=True, type=Path)
    args = parser.parse_args()

    names = enum_platforms(args.hermes_repo) | plugin_platforms(args.hermes_repo)
    bad = sorted(name for name in names if not NAME_RE.match(name))
    if bad:
        raise SystemExit(f"FATAL: non-conforming platform names: {bad}")
    if "api_server" not in names:
        raise SystemExit("FATAL: api_server missing from the enumerated platforms")
    if len(names) < MIN_EXPECTED:
        raise SystemExit(
            f"FATAL: only {len(names)} platforms enumerated (< {MIN_EXPECTED}) — "
            "generation is broken, refusing to write a partial disable list"
        )

    lines = ["", "# GENERATED by generate_platforms.py (C24) — do not hand-edit."]
    lines.append("platforms:")
    lines.append("  api_server:")
    lines.append("    enabled: true")
    for name in sorted(names - {"api_server"}):
        lines.append(f"  {name}: {{ enabled: false }}")
    lines.append("")

    config = args.config
    text = config.read_text() if config.exists() else ""
    if re.search(r"^platforms:", text, flags=re.M):
        raise SystemExit(
            f"FATAL: {config} already contains a platforms block — "
            "refusing to append a second one"
        )
    config.write_text(text.rstrip("\n") + "\n" + "\n".join(lines))
    print(
        f"platforms block generated: {len(names)} adapters, api_server only enabled",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
