#!/usr/bin/env bash
# air 2.0 — M0 template box setup.
# Run ONCE inside the template Box (created with noEnv:false, ttlSeconds:null,
# size default 4 vCPU / 8 GB). User forks are created with noEnv:true.
set -euo pipefail

HERMES_REPO="${HERMES_REPO:-https://github.com/NousResearch/hermes-agent.git}"
# V0: pinned Hermes revision (C24 depends on knowing exactly which snapshot the
# template runs). Tag v2026.8.16.2 == pyproject version 0.20.3 (release line
# v0.20.2, 2026-08-16). Re-pin deliberately with a delta review — never float
# back to main (goal.md §12.4).
HERMES_REF="${HERMES_REF:-7339f5f160db5c96657a3bab60151227cc61f66c}"
HOME_DIR="${HOME:-/home/user}"

# ── 1. Hermes from source at the pinned revision ────────────────────────
if [ ! -d "$HOME_DIR/hermes-agent/.git" ]; then
  # init+fetch instead of clone --branch: works for tags AND bare commit SHAs.
  git init "$HOME_DIR/hermes-agent"
  git -C "$HOME_DIR/hermes-agent" remote add origin "$HERMES_REPO"
fi
git -C "$HOME_DIR/hermes-agent" fetch --depth 1 origin "$HERMES_REF"
git -C "$HOME_DIR/hermes-agent" checkout --force FETCH_HEAD
RESOLVED_HERMES_SHA=$(git -C "$HOME_DIR/hermes-agent" rev-parse HEAD)
mkdir -p "$HOME_DIR/.hermes"
printf '%s\n' "$RESOLVED_HERMES_SHA" > "$HOME_DIR/.hermes/.template-hermes-ref"
cd "$HOME_DIR/hermes-agent"
command -v uv >/dev/null || curl -LsSf https://astral.sh/uv/install.sh | sh

# The venv lives OUTSIDE the git checkout: box archive/restore drops
# gitignored paths inside the repo (same reason web_dist is copied out), and
# `uv run`'s implicit sync would strip the [all] extras (aiohttp → api_server
# dies). So: persistent env at ~/.hermes-venv + UV_NO_SYNC everywhere.
HERMES_VENV="$HOME_DIR/.hermes-venv"
uv venv "$HERMES_VENV" --python 3.11 || true
UV_PROJECT_ENVIRONMENT="$HERMES_VENV" uv pip install -e ".[all]" --python "$HERMES_VENV/bin/python"
grep -q UV_NO_SYNC "$HOME_DIR/.bashrc" || {
  echo "export UV_NO_SYNC=1" >> "$HOME_DIR/.bashrc"
  echo "export UV_PROJECT_ENVIRONMENT=$HERMES_VENV" >> "$HOME_DIR/.bashrc"
}
grep -q UV_NO_SYNC /etc/environment || {
  echo "UV_NO_SYNC=1" | sudo tee -a /etc/environment >/dev/null
  echo "UV_PROJECT_ENVIRONMENT=$HERMES_VENV" | sudo tee -a /etc/environment >/dev/null
}

# ── 2. Build the dashboard SPA at template time ─────────────────────────────
# Otherwise every forked box shells out to npm on first launch.
# web/vite.config.ts builds into ../hermes_cli/web_dist.
# Node 24 via nvm: the box's system node (v20) fails hermes-agent's engine
# check, and nvm-installed versions live in $HOME so they survive archive.
export NVM_DIR="$HOME_DIR/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] || { curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash; }
. "$NVM_DIR/nvm.sh"
nvm install 24 && nvm alias default 24

(cd web && npm ci && npm run build)
test -n "$(ls -A hermes_cli/web_dist 2>/dev/null)" || {
  echo "FATAL: hermes_cli/web_dist/ is empty — dashboard SPA did not build" >&2
  exit 1
}

# ── 3. Seed ~/.hermes/config.yaml ───────────────────────────────────────────
# approvals on; terminal.backend local (the Box IS the computer); model.base_url
# points at the gateway placeholder (rewritten per-fork by the control plane);
# every messaging platform explicitly disabled except api_server (C12); the
# platforms block is GENERATED from the pinned snapshot, never hand-written
# (C24) — an upstream adapter (photon above all) must never silently open a
# second door into the agent.
mkdir -p "$HOME_DIR/.hermes"
cat > "$HOME_DIR/.hermes/config.yaml" <<'YAML'
approvals:
  mode: "smart"

terminal:
  backend: "local"

# The box IS the computer: launch the agent browser headed on the box's X
# display so the human can watch/act via the desktop stream (computer relay).
# backend is pinned explicitly (V0 task 3b): "off" = the built-in browser_*
# tools over the baked agent-browser CLI — the behavior v2 shipped — rather
# than inheriting 0.20.x's browser_exec-when-CLI-present default.
browser:
  headed: true
  backend: "off"

model:
  default: "balanced"
  provider: "custom"
  base_url: "https://GATEWAY_PLACEHOLDER/api/gateway/v1"

# V7 substrate: named profiles serve under /p/<name>/ with per-profile keys.
gateway:
  multiplex_profiles: true
YAML

# ── 3a. C24: generate the platform-disable list from the pinned snapshot ────
# Enumerate gateway.config.Platform ∪ plugins/platforms/*/ and append
# `enabled: false` for every adapter except api_server. Build FAILS if
# generation fails (set -e) or produces an implausibly small set.
TEMPLATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
"$HERMES_VENV/bin/python" "$TEMPLATE_DIR/generate_platforms.py" \
  --hermes-repo "$HOME_DIR/hermes-agent" \
  --config "$HOME_DIR/.hermes/config.yaml"

# ── 3b. Seed ~/.hermes/.env with template-time secrets ──────────────────────
# API_SERVER_KEY and the dashboard basic-auth credentials are per-box secrets
# regenerated by the control plane at fork; these are template placeholders
# strong enough to boot and warm the services.
TEMPLATE_API_SERVER_KEY=$(openssl rand -hex 32)
TEMPLATE_DASH_PASSWORD=$(openssl rand -hex 16)
TEMPLATE_DASH_SECRET=$(openssl rand -hex 32)
TEMPLATE_DASH_HASH=$(cd "$HOME_DIR/hermes-agent" && "$HERMES_VENV/bin/python" -c "from plugins.dashboard_auth.basic import hash_password; print(hash_password('$TEMPLATE_DASH_PASSWORD'))")
cat > "$HOME_DIR/.hermes/.env" <<ENV
API_SERVER_KEY=$TEMPLATE_API_SERVER_KEY
API_SERVER_HOST=0.0.0.0
OPENAI_API_KEY=GATEWAY_TOKEN_PLACEHOLDER
HERMES_DASHBOARD_BASIC_AUTH_USERNAME=air
HERMES_DASHBOARD_BASIC_AUTH_PASSWORD_HASH=$TEMPLATE_DASH_HASH
HERMES_DASHBOARD_BASIC_AUTH_SECRET=$TEMPLATE_DASH_SECRET
DISPLAY=:0
AGENT_BROWSER_ARGS=--no-sandbox
ENV
chmod 600 "$HOME_DIR/.hermes/.env"

# ── 3b2. Browser runtime for the computer relay ─────────────────────────────
# Hermes' browser tool shells out to the agent-browser CLI, which needs
# Node >= 22. Both live under $HOME so they survive box archive/restore.
# Chromium runs headed on :0 with --no-sandbox (containerized box).
HERMES_NODE="$HOME_DIR/.hermes/node"
if [ ! -x "$HERMES_NODE/bin/node" ]; then
  curl -fsSLo /tmp/node22.tar.xz https://nodejs.org/dist/v22.22.0/node-v22.22.0-linux-x64.tar.xz
  mkdir -p "$HERMES_NODE"
  tar -xJf /tmp/node22.tar.xz -C "$HERMES_NODE" --strip-components=1
  rm -f /tmp/node22.tar.xz
fi
export PATH="$HERMES_NODE/bin:$PATH"
npm install -g agent-browser --no-audit --no-fund
agent-browser install   # downloads Chrome for Testing into ~/.agent-browser

# Make the CLI resolvable by the systemd services (they inherit systemd's
# default PATH and only load ~/.hermes/.env, which does no $-expansion) and
# by the agent's local terminal backend.
sed -i '/^PATH=/d' "$HOME_DIR/.hermes/.env"
echo "PATH=$HERMES_NODE/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> "$HOME_DIR/.hermes/.env"
grep -q 'hermes/node/bin' "$HOME_DIR/.bashrc" || \
  echo "export PATH=\"$HERMES_NODE/bin:\$PATH\"" >> "$HOME_DIR/.bashrc"

# ── 3b3. Daytona CLI + MCP: on-demand throwaway code sandboxes ───────────────
# The Box stays the agent's durable home; Daytona sandboxes are ephemeral
# (create → run → destroy) for risky/experimental code. The CLI binary lives
# in /usr/local/bin (snapshotted); auth is `daytona login --api-key <key>`,
# run by the operator at template-prep time (profile persists in ~/.daytona
# and forks inherit it). The MCP server is stdio: `daytona mcp start`.
sudo curl -sfL https://github.com/daytona/clients/releases/latest/download/daytona-linux-amd64 -o /usr/local/bin/daytona
sudo chmod +x /usr/local/bin/daytona
if [ -n "${DAYTONA_API_KEY:-}" ]; then
  /usr/local/bin/daytona login --api-key "$DAYTONA_API_KEY"
fi
printf 'y\n' | "$HERMES_VENV/bin/hermes" mcp add daytona --command /usr/local/bin/daytona --args mcp start \
  || echo "WARN: daytona mcp add failed" >&2

# ── 3c. Preinstall base skills into ~/.hermes/skills ────────────────────────
# On top of the bundled library; forks inherit these so provisioning doesn't
# pay the install cost per user. Failures warn but don't abort the template.
for skill in official/email/agentmail official/research/duckduckgo-search; do
  "$HERMES_VENV/bin/hermes" skills install "$skill" --yes || echo "WARN: base skill $skill install failed" >&2
done

# Bake local skills shipped with this template (e.g. the computer relay,
# which teaches the agent to send its human a live screen card for logins).
TEMPLATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mkdir -p "$HOME_DIR/.hermes/skills"
for local_skill in "$TEMPLATE_DIR"/skills/*/; do
  name="$(basename "$local_skill")"
  rm -rf "$HOME_DIR/.hermes/skills/$name"
  cp -r "$local_skill" "$HOME_DIR/.hermes/skills/$name"
done

# Teach the agent it owns a computer. SOUL.md is auto-loaded into every
# session's context; without this the model defaults to walking the human
# through steps on THEIR device instead of driving its own browser (which is
# what surfaces the live computer view in the web app).
if ! grep -q '## Your own computer' "$HOME_DIR/.hermes/SOUL.md" 2>/dev/null; then
  cat >> "$HOME_DIR/.hermes/SOUL.md" <<'EOF'

## Your own computer
You run on your own Linux computer with a graphical desktop and a real browser
(the browser_* tools). When a task involves a website — navigating a UI,
checking a page, filling forms, signing in somewhere — do it yourself in YOUR
browser. Never instruct the human to open a browser on their own device for
something you can do here. Your human can watch your screen live and take over
at any time (the web app shows your computer inline in Chat, and iMessage users
get a computer card). When a step needs the human — passwords, 2FA codes, OAuth
consents, CAPTCHAs — open the page in your browser, get it to the exact step,
then follow the computer-relay skill to hand them the screen. Never ask for
credentials in chat.
EOF
fi

# M16: make the agent aware of the creative slash commands. They are handled
# by the control plane before Hermes ever sees the message, so this is purely
# awareness — the box never routes or executes them.
if ! grep -q '/imagine, /animate, /zap' "$HOME_DIR/.hermes/SOUL.md" 2>/dev/null; then
  cat >> "$HOME_DIR/.hermes/SOUL.md" <<'EOF'

Your human can also use /imagine, /animate, /zap in chat for instant media — those are handled before you see them.
EOF
fi

# Copy the built SPA outside the git checkout: box archive/restore does not
# preserve gitignored build output inside the repo, so the dashboard serves
# from ~/.hermes/web_dist (HERMES_WEB_DIST) instead.
rm -rf "$HOME_DIR/.hermes/web_dist"
cp -r "$HOME_DIR/hermes-agent/hermes_cli/web_dist" "$HOME_DIR/.hermes/web_dist"
echo "HERMES_WEB_DIST=$HOME_DIR/.hermes/web_dist" >> "$HOME_DIR/.hermes/.env"

# ── 3d. Bake the creative plugin into the template (CM1 task 7 / CC9) ────────
# Plugin API routes mount once at dashboard startup; a rescan will not pick up
# a new plugin_api.py — a plugin version bump means a template rebuild plus a
# documented re-fork or restart window (docs/creative-plugin.md).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mkdir -p "$HOME_DIR/.hermes/plugins"
rm -rf "$HOME_DIR/.hermes/plugins/creative"
cp -r "$SCRIPT_DIR/plugins/creative" "$HOME_DIR/.hermes/plugins/creative"
sed -i '/^CREATIVE_PLUGIN_VERSION=/d' "$HOME_DIR/.hermes/.env"
echo "CREATIVE_PLUGIN_VERSION=$(python3 -c "import json;print(json.load(open('$SCRIPT_DIR/plugins/creative/dashboard/manifest.json'))['version'])")" >> "$HOME_DIR/.hermes/.env"
# ── 3d2. Bake the air-vault plugin (V1 / C18) ────────────────────────────────
# Encrypted store + air-vault CLI + the air_vault mapped secret source. The
# store key (AIR_VAULT_KEY) is minted per-fork by the control plane; the
# template ships only code, never vault data. Plugin dir name uses a dash
# (matches the repo path); Hermes imports it under a sanitized module name,
# and the plugin.yaml name / secret-source name is air_vault.
rm -rf "$HOME_DIR/.hermes/plugins/air-vault"
cp -r "$SCRIPT_DIR/plugins/air-vault" "$HOME_DIR/.hermes/plugins/air-vault"
rm -rf "$HOME_DIR/.hermes/plugins/air-vault/tests"
# The CLI is invoked by the control plane as plain `air-vault ...` over the
# box command API.
# It reads ONLY AIR_VAULT_KEY out of ~/.hermes/.env (never `source`s it —
# other values could contain shell metacharacters).
sudo tee /usr/local/bin/air-vault >/dev/null <<SH
#!/usr/bin/env bash
set -euo pipefail
if [ -z "\${AIR_VAULT_KEY:-}" ] && [ -f "$HOME_DIR/.hermes/.env" ]; then
  AIR_VAULT_KEY="\$(grep -m1 '^AIR_VAULT_KEY=' "$HOME_DIR/.hermes/.env" | cut -d= -f2-)"
  export AIR_VAULT_KEY
fi
exec "$HERMES_VENV/bin/python" "$HOME_DIR/.hermes/plugins/air-vault/cli.py" "\$@"
SH
sudo chmod +x /usr/local/bin/air-vault

# User plugins are opt-in: the dashboard only imports a user plugin's backend
# (plugin_api.py) when its name is in the plugins.enabled allow-list in
# ~/.hermes/config.yaml (GHSA-mcfc-hp25-cjv7). air_vault joins the allow-list
# and its secret source is seeded enabled (fetch degrades to NOT_CONFIGURED
# until provisioning mints AIR_VAULT_KEY).
python3 - "$HOME_DIR/.hermes/config.yaml" <<'PYEOF'
import sys, yaml, pathlib
p = pathlib.Path(sys.argv[1])
cfg = yaml.safe_load(p.read_text()) if p.exists() else None
cfg = cfg if isinstance(cfg, dict) else {}
plugins = cfg.get("plugins")
plugins = plugins if isinstance(plugins, dict) else {}
enabled = plugins.get("enabled")
enabled = enabled if isinstance(enabled, list) else []
for name in ("creative", "air_vault"):
    if name not in enabled:
        enabled.append(name)
plugins["enabled"] = sorted(enabled)
cfg["plugins"] = plugins
secrets = cfg.get("secrets")
secrets = secrets if isinstance(secrets, dict) else {}
air_vault = secrets.get("air_vault")
air_vault = air_vault if isinstance(air_vault, dict) else {}
air_vault["enabled"] = True
secrets["air_vault"] = air_vault
cfg["secrets"] = secrets
p.write_text(yaml.safe_dump(cfg, default_flow_style=False))
PYEOF

# ── 3e. C24 gate: the build fails if any platform but api_server is enabled ──
# Re-checks the FINAL config (after every rewrite above) against the same
# enum ∪ plugin-dir ∪ registered-name union the generator used.
"$HERMES_VENV/bin/python" "$TEMPLATE_DIR/generate_platforms.py" \
  --hermes-repo "$HOME_DIR/hermes-agent" \
  --config "$HOME_DIR/.hermes/config.yaml" \
  --verify

# ── 4. systemd units — /etc is snapshotted, enabled units restart on resume ──
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
sudo cp "$SCRIPT_DIR"/hermes-gateway.service /etc/systemd/system/
sudo cp "$SCRIPT_DIR"/hermes-dashboard.service /etc/systemd/system/
sudo cp "$SCRIPT_DIR"/hermes-host.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable hermes-gateway.service hermes-dashboard.service hermes-host.service
sudo systemctl start hermes-gateway.service hermes-dashboard.service hermes-host.service

echo "Template setup complete."
echo "Next (operator steps, per goal.md M0):"
echo "  1. Verify /health on 8642 and /api/health on 9119 via the hosted URLs."
echo "  2. Warm the template: stop, resume, let Hermes boot fully, stop again."
echo "  3. Record the box id as BOX_TEMPLATE_ID."
