#!/usr/bin/env bash
# air 2.0 — M0 template box setup.
# Run ONCE inside the template Box (created with noEnv:false, ttlSeconds:null,
# size default 4 vCPU / 8 GB). User forks are created with noEnv:true.
set -euo pipefail

HERMES_REPO="${HERMES_REPO:-https://github.com/NousResearch/hermes-agent.git}"
HOME_DIR="${HOME:-/home/user}"

# ── 1. Hermes from source, with the extras the dashboard needs ──────────────
if [ ! -d "$HOME_DIR/hermes-agent" ]; then
  git clone --depth 1 "$HERMES_REPO" "$HOME_DIR/hermes-agent"
fi
cd "$HOME_DIR/hermes-agent"
command -v uv >/dev/null || curl -LsSf https://astral.sh/uv/install.sh | sh

# The venv lives OUTSIDE the git checkout: box archive/restore drops
# gitignored paths inside the repo (same reason web_dist is copied out), and
# `uv run`'s implicit sync would strip the [all] extras (aiohttp → api_server
# dies). So: persistent env at ~/.hermes-venv + UV_NO_SYNC everywhere.
HERMES_VENV="$HOME_DIR/.hermes-venv"
uv venv "$HERMES_VENV" --python 3.11 || true
UV_PROJECT_ENVIRONMENT="$HERMES_VENV" uv pip install -e ".[all]" --python "$HERMES_VENV/bin/python"
grep -q UV_NO_SYNC "$HOME_DIR/.bashrc" || {
  echo "export UV_NO_SYNC=1" >> "$HOME_DIR/.bashrc"
  echo "export UV_PROJECT_ENVIRONMENT=$HERMES_VENV" >> "$HOME_DIR/.bashrc"
}
grep -q UV_NO_SYNC /etc/environment || {
  echo "UV_NO_SYNC=1" | sudo tee -a /etc/environment >/dev/null
  echo "UV_PROJECT_ENVIRONMENT=$HERMES_VENV" | sudo tee -a /etc/environment >/dev/null
}

# ── 2. Build the dashboard SPA at template time ─────────────────────────────
# Otherwise every forked box shells out to npm on first launch.
# web/vite.config.ts builds into ../hermes_cli/web_dist.
# Node 24 via nvm: the box's system node (v20) fails hermes-agent's engine
# check, and nvm-installed versions live in $HOME so they survive archive.
export NVM_DIR="$HOME_DIR/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] || { curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash; }
. "$NVM_DIR/nvm.sh"
nvm install 24 && nvm alias default 24

(cd web && npm ci && npm run build)
test -n "$(ls -A hermes_cli/web_dist 2>/dev/null)" || {
  echo "FATAL: hermes_cli/web_dist/ is empty — dashboard SPA did not build" >&2
  exit 1
}

# ── 3. Seed ~/.hermes/config.yaml ───────────────────────────────────────────
# approvals on; terminal.backend local (the Box IS the computer); model.base_url
# points at the gateway placeholder (rewritten per-fork by the control plane);
# every messaging platform explicitly disabled except api_server (C12).
mkdir -p "$HOME_DIR/.hermes"
cat > "$HOME_DIR/.hermes/config.yaml" <<'YAML'
approvals:
  mode: "smart"

terminal:
  backend: "local"

model:
  default: "balanced"
  provider: "custom"
  base_url: "https://GATEWAY_PLACEHOLDER/api/gateway/v1"

platforms:
  api_server:
    enabled: true
  bluebubbles: { enabled: false }
  telegram: { enabled: false }
  discord: { enabled: false }
  slack: { enabled: false }
  signal: { enabled: false }
  whatsapp: { enabled: false }
  whatsapp_cloud: { enabled: false }
  email: { enabled: false }
  sms: { enabled: false }
  matrix: { enabled: false }
  mattermost: { enabled: false }
  dingtalk: { enabled: false }
  feishu: { enabled: false }
  wecom: { enabled: false }
  weixin: { enabled: false }
  qqbot: { enabled: false }
  yuanbao: { enabled: false }
  webhook: { enabled: false }
  msgraph_webhook: { enabled: false }
  relay: { enabled: false }
YAML

# ── 3b. Seed ~/.hermes/.env with template-time secrets ──────────────────────
# API_SERVER_KEY and the dashboard basic-auth credentials are per-box secrets
# regenerated by the control plane at fork; these are template placeholders
# strong enough to boot and warm the services.
TEMPLATE_API_SERVER_KEY=$(openssl rand -hex 32)
TEMPLATE_DASH_PASSWORD=$(openssl rand -hex 16)
TEMPLATE_DASH_SECRET=$(openssl rand -hex 32)
TEMPLATE_DASH_HASH=$(cd "$HOME_DIR/hermes-agent" && "$HERMES_VENV/bin/python" -c "from plugins.dashboard_auth.basic import hash_password; print(hash_password('$TEMPLATE_DASH_PASSWORD'))")
cat > "$HOME_DIR/.hermes/.env" <<ENV
API_SERVER_KEY=$TEMPLATE_API_SERVER_KEY
API_SERVER_HOST=0.0.0.0
OPENAI_API_KEY=GATEWAY_TOKEN_PLACEHOLDER
HERMES_DASHBOARD_BASIC_AUTH_USERNAME=air
HERMES_DASHBOARD_BASIC_AUTH_PASSWORD_HASH=$TEMPLATE_DASH_HASH
HERMES_DASHBOARD_BASIC_AUTH_SECRET=$TEMPLATE_DASH_SECRET
ENV
chmod 600 "$HOME_DIR/.hermes/.env"

# ── 3c. Preinstall base skills into ~/.hermes/skills ────────────────────────
# On top of the bundled library; forks inherit these so provisioning doesn't
# pay the install cost per user. Failures warn but don't abort the template.
for skill in official/email/agentmail official/research/duckduckgo-search; do
  "$HERMES_VENV/bin/hermes" skills install "$skill" --yes || echo "WARN: base skill $skill install failed" >&2
done

# Bake local skills shipped with this template (e.g. the computer relay,
# which teaches the agent to send its human a live screen card for logins).
TEMPLATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mkdir -p "$HOME_DIR/.hermes/skills"
for local_skill in "$TEMPLATE_DIR"/skills/*/; do
  name="$(basename "$local_skill")"
  rm -rf "$HOME_DIR/.hermes/skills/$name"
  cp -r "$local_skill" "$HOME_DIR/.hermes/skills/$name"
done

# Copy the built SPA outside the git checkout: box archive/restore does not
# preserve gitignored build output inside the repo, so the dashboard serves
# from ~/.hermes/web_dist (HERMES_WEB_DIST) instead.
rm -rf "$HOME_DIR/.hermes/web_dist"
cp -r "$HOME_DIR/hermes-agent/hermes_cli/web_dist" "$HOME_DIR/.hermes/web_dist"
echo "HERMES_WEB_DIST=$HOME_DIR/.hermes/web_dist" >> "$HOME_DIR/.hermes/.env"

# ── 3d. Bake the creative plugin into the template (CM1 task 7 / CC9) ────────
# Plugin API routes mount once at dashboard startup; a rescan will not pick up
# a new plugin_api.py — a plugin version bump means a template rebuild plus a
# documented re-fork or restart window (docs/creative-plugin.md).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mkdir -p "$HOME_DIR/.hermes/plugins"
rm -rf "$HOME_DIR/.hermes/plugins/creative"
cp -r "$SCRIPT_DIR/plugins/creative" "$HOME_DIR/.hermes/plugins/creative"
sed -i '/^CREATIVE_PLUGIN_VERSION=/d' "$HOME_DIR/.hermes/.env"
echo "CREATIVE_PLUGIN_VERSION=$(python3 -c "import json;print(json.load(open('$SCRIPT_DIR/plugins/creative/dashboard/manifest.json'))['version'])")" >> "$HOME_DIR/.hermes/.env"
# User plugins are opt-in: the dashboard only imports a user plugin's backend
# (plugin_api.py) when its name is in the plugins.enabled allow-list in
# ~/.hermes/config.yaml (GHSA-mcfc-hp25-cjv7).
python3 - "$HOME_DIR/.hermes/config.yaml" <<'PYEOF'
import sys, yaml, pathlib
p = pathlib.Path(sys.argv[1])
cfg = yaml.safe_load(p.read_text()) if p.exists() else None
cfg = cfg if isinstance(cfg, dict) else {}
plugins = cfg.get("plugins")
plugins = plugins if isinstance(plugins, dict) else {}
enabled = plugins.get("enabled")
enabled = enabled if isinstance(enabled, list) else []
if "creative" not in enabled:
    enabled.append("creative")
plugins["enabled"] = sorted(enabled)
cfg["plugins"] = plugins
p.write_text(yaml.safe_dump(cfg, default_flow_style=False))
PYEOF

# ── 4. systemd units — /etc is snapshotted, enabled units restart on resume ──
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
sudo cp "$SCRIPT_DIR"/hermes-gateway.service /etc/systemd/system/
sudo cp "$SCRIPT_DIR"/hermes-dashboard.service /etc/systemd/system/
sudo cp "$SCRIPT_DIR"/hermes-host.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable hermes-gateway.service hermes-dashboard.service hermes-host.service
sudo systemctl start hermes-gateway.service hermes-dashboard.service hermes-host.service

echo "Template setup complete."
echo "Next (operator steps, per goal.md M0):"
echo "  1. Verify /health on 8642 and /api/health on 9119 via the hosted URLs."
echo "  2. Warm the template: stop, resume, let Hermes boot fully, stop again."
echo "  3. Record the box id as BOX_TEMPLATE_ID."
