/**
 * Bot provisioning (V7): one Hermes profile per bot on the user's ONE box.
 * Mirrors lib/provisioning/provision.ts discipline — do the box work first,
 * verify health, only then persist the row; roll the half-made profile back
 * on any failure.
 *
 * The profile .env carries exactly the api_server switch, a FRESH per-profile
 * API_SERVER_KEY, and the box's GATEWAY_TOKEN as OPENAI_API_KEY pointed at
 * the control-plane gateway (C21) — zero provider keys ever enter the box
 * (C2). The platforms block is the C24-generated block (copied from the main
 * config the template generated from the pinned snapshot), so a bot profile
 * gets the same all-off-except-api_server posture as the box itself (C12).
 */
import { randomBytes } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import { env } from "../env";
import { command } from "../box/client";
import { health, deleteJob, listJobs } from "../hermes/client";
import { ensureBoxAwake, type UserBox } from "../orchestrator/boxes";
import { botTarget, BOT_NAME_PATTERN, isValidBotName } from "./client";
import type { BotAvatarKind, BotModelTier, BotRow } from "./store";

const HERMES_BIN = "/home/user/.hermes-venv/bin/hermes";
const PROFILES_DIR = "/home/user/.hermes/profiles";
const MAIN_CONFIG = "/home/user/.hermes/config.yaml";
const GENERATED_MARK = "# GENERATED by generate_platforms.py";

export interface CreateBotOptions {
  name: string;
  title?: string;
  description?: string;
  cloneFrom?: string;
  modelTier?: BotModelTier;
  groupLabel?: string;
  avatarKind?: BotAvatarKind;
  avatarRef?: string;
  /** Skill hub identifiers to install into the profile (advanced create). */
  skills?: string[];
}

async function boxGatewayToken(
  supabase: SupabaseClient,
  userId: string
): Promise<string> {
  const { data, error } = await supabase
    .from("boxes")
    .select("gateway_token")
    .eq("user_id", userId)
    .maybeSingle();
  if (error || !data?.gateway_token) {
    throw new Error(`gateway token lookup failed: ${error?.message ?? "no box"}`);
  }
  return data.gateway_token as string;
}

async function run(
  boxId: string,
  cmd: string,
  timeoutSeconds = 120
): Promise<string> {
  const result = await command(boxId, cmd, timeoutSeconds);
  if (result.exitCode !== 0) {
    throw new Error(`box command failed: ${result.stderr.slice(0, 300)}`);
  }
  return result.stdout;
}

/** Best-effort teardown of a half-made (or deleted) profile. */
async function removeProfile(boxId: string, name: string): Promise<void> {
  if (!BOT_NAME_PATTERN.test(name) || name === "default") return;
  await command(
    boxId,
    `${HERMES_BIN} profile delete ${name} --yes || rm -rf ${PROFILES_DIR}/${name}`,
    120
  ).catch(() => undefined);
}

async function restartGateway(boxId: string): Promise<void> {
  await run(boxId, "sudo systemctl restart hermes-gateway", 120);
}

/**
 * Provision the profile on the box and insert the bots row. Throws on any
 * failure after deleting the half-made profile (rollback), so no orphan
 * profile dir and no bots row survive a failed create.
 */
export async function provisionBot(
  supabase: SupabaseClient,
  userId: string,
  options: CreateBotOptions
): Promise<BotRow> {
  const name = options.name;
  if (!isValidBotName(name)) {
    throw new Error("invalid bot name: [a-z0-9-]{2,32}, not 'default'");
  }
  if (options.cloneFrom !== undefined && !BOT_NAME_PATTERN.test(options.cloneFrom)) {
    throw new Error("invalid clone source");
  }

  const box = await ensureBoxAwake(supabase, userId);
  const gatewayToken = await boxGatewayToken(supabase, userId);
  const gatewayUrl = `${env.appOrigin()}/api/gateway/v1`;
  const apiServerKey = randomBytes(32).toString("hex");

  try {
    // 1. Create (or clone) the profile.
    const cloneFlag =
      options.cloneFrom && options.cloneFrom !== "default"
        ? ` --clone-from ${options.cloneFrom}`
        : options.cloneFrom === "default"
          ? " --clone"
          : "";
    await run(box.boxId, `${HERMES_BIN} profile create ${name}${cloneFlag}`, 180);

    // 2. Profile .env — exactly the api_server switch, a fresh per-profile
    // key, and the gateway credential. Written wholesale so a cloned .env
    // can never carry the source profile's key forward (C2/C3).
    const profileEnv = [
      "API_SERVER_ENABLED=true",
      `API_SERVER_KEY=${apiServerKey}`,
      `OPENAI_API_KEY=${gatewayToken}`,
      `OPENAI_BASE_URL=${gatewayUrl}`,
      "",
    ].join("\n");
    const envB64 = Buffer.from(profileEnv, "utf8").toString("base64");
    await run(
      box.boxId,
      `mkdir -p ${PROFILES_DIR}/${name} && echo '${envB64}' | base64 -d > ${PROFILES_DIR}/${name}/.env && chmod 600 ${PROFILES_DIR}/${name}/.env`
    );

    // 3. Profile config.yaml — a fresh config surface: bot-mode protocol on,
    // the gateway as the (only) model provider, optional tier pin, and the
    // C24-generated platforms block copied from the main config so only
    // api_server is enabled (C12/C24).
    const tierLine = options.modelTier
      ? `  default: "${options.modelTier}"\n`
      : "";
    const profileConfig =
      `# Written by the AIR control plane (V7 bots). Do not hand-edit.\n` +
      `approvals:\n  mode: "smart"\n\n` +
      `terminal:\n  backend: "local"\n\n` +
      `browser:\n  headed: true\n  backend: "off"\n\n` +
      `agent:\n  bot_mode_protocol: true\n\n` +
      `model:\n${tierLine}  provider: "custom"\n  base_url: "${gatewayUrl}"\n  api_key: "${gatewayToken}"\n`;
    const configB64 = Buffer.from(profileConfig, "utf8").toString("base64");
    await run(
      box.boxId,
      `echo '${configB64}' | base64 -d > ${PROFILES_DIR}/${name}/config.yaml && ` +
        `sed -n '/^${GENERATED_MARK.replace(/\//g, "\\/")}/,$p' ${MAIN_CONFIG} >> ${PROFILES_DIR}/${name}/config.yaml && ` +
        `grep -q 'api_server:' ${PROFILES_DIR}/${name}/config.yaml`
    );

    // 4. profile.yaml ui_meta['hermes-bots'] — the bot-mode probe's
    // "is this install Bot-Mode-managed" marker (tools/bot_mode_probe.py).
    const profileMeta =
      `ui_meta:\n  hermes-bots:\n    managed: true\n    bot: "${name}"\n`;
    const metaB64 = Buffer.from(profileMeta, "utf8").toString("base64");
    await run(
      box.boxId,
      `if [ -f ${PROFILES_DIR}/${name}/profile.yaml ] && grep -q '^ui_meta:' ${PROFILES_DIR}/${name}/profile.yaml; then true; else echo '${metaB64}' | base64 -d >> ${PROFILES_DIR}/${name}/profile.yaml; fi`
    );

    // 5. Optional per-skill enablement (advanced create) — best-effort; the
    // profile works without them and the user can install more later.
    for (const skill of options.skills ?? []) {
      // Alnum segments joined by single '.', '/', '_', '-', or '@' — no
      // leading/trailing separators and no '..', so no path traversal.
      if (!/^[A-Za-z0-9]+(?:[@/._-][A-Za-z0-9]+)*$/.test(skill)) continue;
      await command(
        box.boxId,
        `HERMES_HOME=${PROFILES_DIR}/${name} ${HERMES_BIN} skills install "${skill}" --yes`,
        180
      ).catch(() => undefined);
    }

    // 6. The template writes gateway.multiplex_profiles: true (V0); assert
    // rather than trust, appending it if a pre-V0 box is missing it.
    await run(
      box.boxId,
      `grep -q 'multiplex_profiles: true' ${MAIN_CONFIG} || printf '\\ngateway:\\n  multiplex_profiles: true\\n' >> ${MAIN_CONFIG}`
    );

    // 7. Restart the gateway so it mounts /p/<name>/, then probe health
    // with the bot's OWN key (per-profile auth end-to-end).
    await restartGateway(box.boxId);
    const target = botTarget(box.target, name, apiServerKey);
    const deadline = Date.now() + 120_000;
    while (!(await health(target))) {
      if (Date.now() > deadline) {
        throw new Error(`/p/${name}/health not green after gateway restart`);
      }
      await new Promise((resolve) => setTimeout(resolve, 5_000));
    }

    // 8. Only now persist the row.
    const { data, error } = await supabase
      .from("bots")
      .insert({
        user_id: userId,
        name,
        title: options.title ?? null,
        description: options.description ?? null,
        avatar_kind: options.avatarKind ?? "geometric",
        avatar_ref: options.avatarRef ?? null,
        model_tier: options.modelTier ?? null,
        api_server_key: apiServerKey,
        status: "ready",
        group_label: options.groupLabel ?? null,
      })
      .select(
        "id, user_id, name, title, description, avatar_kind, avatar_ref, model_tier, api_server_key, status, group_label, created_at"
      )
      .single();
    if (error || !data) {
      throw new Error(`bots insert failed: ${error?.message}`);
    }
    return data as BotRow;
  } catch (error) {
    await removeProfile(box.boxId, name);
    await restartGateway(box.boxId).catch(() => undefined);
    throw error;
  }
}

/**
 * Delete a bot completely: its `[bot:<name>]` cron jobs, the profile dir,
 * and the bots row — leaving no profile dir, no jobs, no row.
 */
export async function deleteBot(
  supabase: SupabaseClient,
  userId: string,
  bot: BotRow
): Promise<void> {
  const box = await ensureBoxAwake(supabase, userId);
  const target = botTarget(box.target, bot.name, bot.api_server_key);
  // Cron jobs live inside the profile store; delete explicitly first so a
  // partially-failing profile delete cannot leave live schedules behind.
  try {
    const jobs = await listJobs(target);
    for (const job of jobs) {
      await deleteJob(target, job.id).catch(() => undefined);
    }
  } catch {
    // Profile already unreachable — the dir removal below covers the jobs.
  }
  await removeProfile(box.boxId, bot.name);
  await restartGateway(box.boxId).catch(() => undefined);
  const { error } = await supabase.from("bots").delete().eq("id", bot.id);
  if (error) {
    throw new Error(`bots delete failed: ${error.message}`);
  }
}

/** Re-pin (or clear) a bot's model tier in its profile config. */
export async function applyModelTier(
  box: UserBox,
  name: string,
  tier: BotModelTier | null
): Promise<void> {
  if (!BOT_NAME_PATTERN.test(name)) throw new Error("invalid bot name");
  const config = `${PROFILES_DIR}/${name}/config.yaml`;
  if (tier) {
    await run(
      box.boxId,
      `sed -i -e '/^  default:/d' -e 's|^model:$|model:\\n  default: "${tier}"|' ${config}`
    );
  } else {
    await run(box.boxId, `sed -i -e '/^  default:/d' ${config}`);
  }
  await restartGateway(box.boxId);
}
