/**
 * Storage glue between the GMI provider and the existing creative asset
 * pipeline (0011_creative_assets.sql). Validated provider bytes land
 * content-addressed in the private creative-assets bucket (sha256 dedupe),
 * and browsers/iMessage only ever see short-TTL signed delivery URLs — a
 * provider URL never leaves the control plane.
 */
import { createHash, randomBytes } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import {
  ASSETS_BUCKET,
  contentType,
  DELIVERY_TTL_SECONDS,
  masterKey,
} from "../assets/keys";
import {
  AssetPipelineError,
  mintDelivery,
  type CreativeAsset,
  type Delivery,
} from "../assets/pipeline";
import { heifToJpeg, isHeif } from "../identity/heif";
import type { FetchedGeneratedMedia } from "./media-url";

const EXT_BY_MIME: Record<string, string> = {
  "image/gif": "gif",
  "image/heic": "jpg",
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "video/mp4": "mp4",
  "video/quicktime": "mov",
  "video/webm": "webm",
};

export const deliveryPurpose = (jobId: string): string => `creative:${jobId}`;

/** Content-addressed ingest shared by provider downloads and owner uploads. */
async function ingestBytes(
  supabase: SupabaseClient,
  userId: string,
  bytes: Buffer,
  mimeType: string,
  refPrefix: string
): Promise<CreativeAsset> {
  const ext = EXT_BY_MIME[mimeType];
  if (!ext) {
    throw new AssetPipelineError("media has an unsupported type");
  }
  const digest = createHash("sha256").update(bytes).digest("hex");

  const existing = await supabase
    .from("creative_assets")
    .select("*")
    .eq("user_id", userId)
    .eq("sha256", digest)
    .maybeSingle();
  if (existing.data) {
    return existing.data as CreativeAsset;
  }

  const key = masterKey(userId, digest, ext);
  const upload = await supabase.storage
    .from(ASSETS_BUCKET)
    .upload(key, bytes, { contentType: contentType(ext), upsert: true });
  if (upload.error) {
    throw new AssetPipelineError(
      `storage upload failed: ${upload.error.message}`
    );
  }

  const inserted = await supabase
    .from("creative_assets")
    .insert({
      user_id: userId,
      // Not a box-side asset: record the origin as the ref.
      box_asset_id: `${refPrefix}:${digest}`,
      sha256: digest,
      ext,
      kind: ext,
      bytes: bytes.byteLength,
      storage_key: key,
    })
    .select("*")
    .single();
  if (inserted.error) {
    throw new AssetPipelineError(inserted.error.message);
  }
  return inserted.data as CreativeAsset;
}

/**
 * Store validated generated bytes through the existing content-addressed
 * pipeline. Idempotent: identical bytes land on the existing row/object.
 */
export async function ingestGeneratedMedia(
  supabase: SupabaseClient,
  userId: string,
  media: FetchedGeneratedMedia
): Promise<CreativeAsset> {
  return await ingestBytes(supabase, userId, media.bytes, media.mimeType, "gmi");
}

/**
 * Store owner-uploaded bytes (already guarded by guardMediaUpload) through
 * the same content-addressed pipeline as generated media.
 */
export async function ingestUploadedMedia(
  supabase: SupabaseClient,
  userId: string,
  bytes: Buffer,
  mimeType: string
): Promise<CreativeAsset> {
  return await ingestBytes(supabase, userId, bytes, mimeType, "upload");
}

/** Mint the short-TTL delivery URL for one creative job's output. */
export async function mintJobDelivery(
  supabase: SupabaseClient,
  asset: CreativeAsset,
  jobId: string
): Promise<Delivery> {
  return await mintDelivery(supabase, asset, deliveryPurpose(jobId));
}

/**
 * Re-sign the delivered object for a job (the signed URL itself is never
 * stored — C4). Returns undefined until the job's delivery exists.
 */
export async function signedDeliveryForJob(
  supabase: SupabaseClient,
  userId: string,
  jobId: string
): Promise<{ url: string; ext: string } | undefined> {
  const { data } = await supabase
    .from("asset_deliveries")
    .select("storage_key, expires_at, revoked_at")
    .eq("user_id", userId)
    .eq("purpose", deliveryPurpose(jobId))
    .is("revoked_at", null)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  const storageKey = data?.storage_key as string | undefined;
  if (!storageKey) return undefined;
  const signed = await supabase.storage
    .from(ASSETS_BUCKET)
    .createSignedUrl(storageKey, DELIVERY_TTL_SECONDS);
  if (signed.error || !signed.data) return undefined;
  return {
    url: signed.data.signedUrl,
    ext: storageKey.split(".").at(-1) ?? "",
  };
}

/**
 * Stage an inbound attachment as a short-lived signed input URL for the
 * provider (edit source / first frame / reference). The object lives under
 * the user's prefix so account deletion removes it with the rest.
 *
 * iPhone attachments arrive as HEIC, which no generation provider accepts as
 * an input image, so they are decoded to JPEG here — before the object and
 * its signed URL exist — and staged as image/jpeg.
 */
export async function stageCreativeInput(
  supabase: SupabaseClient,
  userId: string,
  bytes: Buffer,
  mimeType: string
): Promise<
  | { url: string; kind: "image" | "video"; mimeType: string; storageKey: string }
  | undefined
> {
  let staged = bytes;
  let stagedType = mimeType;
  if (isHeif(stagedType, staged)) {
    try {
      staged = await heifToJpeg(staged);
      stagedType = "image/jpeg";
    } catch {
      return undefined;
    }
  }
  const ext = EXT_BY_MIME[stagedType];
  if (!ext) return undefined;
  const kind = stagedType.startsWith("video/") ? ("video" as const) : ("image" as const);
  const key = `${userId}/deliveries/${randomBytes(16).toString("hex")}.${ext}`;
  const upload = await supabase.storage
    .from(ASSETS_BUCKET)
    .upload(key, staged, { contentType: contentType(ext) });
  if (upload.error) return undefined;
  const signed = await supabase.storage
    .from(ASSETS_BUCKET)
    .createSignedUrl(key, DELIVERY_TTL_SECONDS);
  if (signed.error || !signed.data) {
    await supabase.storage.from(ASSETS_BUCKET).remove([key]).catch(() => undefined);
    return undefined;
  }
  // The key is unguessable and the signature expires with the URL; the
  // caller removes the object once the generation settles.
  return { url: signed.data.signedUrl, kind, mimeType: stagedType, storageKey: key };
}

/** Remove staged provider-input objects once the generation settles. */
export async function removeStagedInputs(
  supabase: SupabaseClient,
  storageKeys: readonly string[]
): Promise<void> {
  if (storageKeys.length === 0) return;
  await supabase.storage
    .from(ASSETS_BUCKET)
    .remove([...storageKeys])
    .catch(() => undefined);
}
