/**
 * kit/air/theme.css and kit/air/shell.css are generated from the platform's
 * theme/shell sources so the Kit can never drift from what mini.wzrd.tech
 * renders. kit/air/index.ts is hand-written (it is the Apps API client).
 */
import fs from "node:fs";
import path from "node:path";
import { THEMES, THEME_IDS, DEFAULT_THEME, tokenBlock, type ThemeId } from "../../../../apps/web/lib/miniapps/themes.ts";
import { KIT_DIR, REPO_ROOT } from "./paths.ts";
import { readText, writeText } from "./fsx.ts";

const SHELL_TS = path.join(REPO_ROOT, "apps/web/lib/miniapps/shell.ts");
const FONTS_SRC = path.join(REPO_ROOT, "apps/web/public/creator-os/fonts");
const AIR_DIR = path.join(KIT_DIR, "air");

const HEADER = (from: string) =>
  `/* GENERATED by packages/create-kit/scripts/harvest.ts from ${from}. Do not edit; edit the source and re-run harvest. */\n`;

function templateLiteral(src: string, name: string): string {
  const re = new RegExp(`const ${name} = \`([\\s\\S]*?)\`;`);
  const m = re.exec(src);
  if (!m) throw new Error(`${name} not found in shell.ts`);
  return m[1]!.replace(/\$\{([A-Z_]+)\}/g, (_all, ident: string) => stringConst(src, ident));
}

/** Value of `const IDENT = "...";` (a plain string literal, possibly wrapped onto the next line). */
function stringConst(src: string, ident: string): string {
  const m = new RegExp(`const ${ident} =\\s*"((?:[^"\\\\]|\\\\.)*)";`).exec(src);
  if (!m) throw new Error(`${ident} not found in shell.ts`);
  return m[1]!;
}

/** `:root{--a:b;--c:d}` → indented block under `selector`. */
function tokenRules(id: ThemeId, selector: string): string {
  const block = tokenBlock(THEMES[id].tokens);
  const inner = block.slice(block.indexOf("{") + 1, -1);
  const lines = inner.split(";").map((d) => `  ${d.trim()};`);
  return `${selector} {\n${lines.join("\n")}\n}\n`;
}

/** Rewrite `/creator-os/fonts/x.woff2` to a Kit-relative URL and split @font-face rules. */
function fontFaces(): string {
  const faces: string[] = [];
  for (const id of THEME_IDS) {
    const ff = THEMES[id].fontFaces;
    if (!ff) continue;
    for (const rule of ff.split("}").filter(Boolean)) {
      const local = rule.replace(/url\(\/creator-os\/fonts\//g, "url(./fonts/");
      if (!faces.includes(local + "}")) faces.push(local + "}");
    }
  }
  return faces.join("\n") + "\n";
}

function prefixLite(css: string): string {
  const out: string[] = [];
  for (const m of css.matchAll(/([^{}]+)\{([^}]*)\}/g)) {
    const selectors = m[1]!.trim().split(",").map((s) => s.trim());
    const prefixed = selectors.map((s) => (s === "html" ? 'html[data-lite="1"]' : `html[data-lite="1"] ${s}`));
    out.push(`${prefixed.join(",")}{${m[2]!.trim()}}`);
  }
  return out.join("\n") + "\n";
}

const TAILWIND_BRIDGE = `
/* Token bridge for the Build Service utility-class pass (Tailwind v4 syntax;
 * inert in a plain stylesheet). bg-canvas, text-ink, text-ink-muted, bg-panel,
 * bg-well, ring-ring, rounded-panel, rounded-well, rounded-pill, font-body,
 * font-ui. */
@theme inline {
  --color-canvas: var(--canvas);
  --color-ink: var(--ink);
  --color-ink-muted: var(--ink-muted);
  --color-on-accent: var(--on-accent);
  --color-on-ink: var(--on-ink);
  --color-accent: var(--accent);
  --color-panel: var(--panel-bg);
  --color-well: var(--well-bg);
  --color-ring: var(--ring);
  --shadow-panel: var(--shadow);
  --radius-panel: var(--radius-panel);
  --radius-well: var(--radius-well);
  --radius-pill: var(--radius-pill);
  --font-body: var(--font-body);
  --font-ui: var(--font-ui);
}
`;

const REDUCED_MOTION = `
/* Reduced motion: Kit components read useReducedMotion(); this is the floor for
 * anything that animates with CSS alone. */
@media (prefers-reduced-motion: reduce) {
  :root {
    --slide-in: none;
  }
  *,
  *::before,
  *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
`;

export function buildThemeCss(): string {
  const parts: string[] = [HEADER("apps/web/lib/miniapps/themes.ts")];
  parts.push("\n/* Self-hosted variable faces (font-src 'self'); served next to this file. */\n");
  parts.push(fontFaces());
  parts.push(`\n/* Themes. Default is "${DEFAULT_THEME}"; the Build Service sets <html data-theme>. */\n`);
  for (const id of THEME_IDS) {
    const selector = id === DEFAULT_THEME ? `:root,\nhtml[data-theme="${id}"]` : `html[data-theme="${id}"]`;
    parts.push(tokenRules(id, selector));
    parts.push("\n");
  }
  parts.push('/* Lite: no blur, no fixed backgrounds, no shader. Set <html data-lite="1">. */\n');
  parts.push('html[data-lite="1"] {\n  --blur: none;\n  --slide-in: none;\n}\n');
  parts.push(REDUCED_MOTION);
  parts.push(TAILWIND_BRIDGE);
  return parts.join("");
}

export function buildShellCss(): string {
  const src = readText(SHELL_TS);
  const shell = templateLiteral(src, "SHELL_CSS").trim();
  const lite = templateLiteral(src, "LITE_CSS").trim();
  return (
    HEADER("apps/web/lib/miniapps/shell.ts (SHELL_CSS + LITE_CSS)") +
    "\n/* Shell vocabulary: .frame, header.bar, .logo-pill, .app-pill, main.app, .panel, .notice,\n" +
    " * .kicker, .muted, .row, .row.actions, .item, .card, .tile, .grid, .cols, .col, .chip, .addrow,\n" +
    " * .tablewrap, .avatar, .hero, .navlink. Touch targets ≥44px; inputs ≥16px. */\n" +
    shell +
    "\n\n/* Lite variant (LITE_CSS), scoped to <html data-lite=\"1\">. */\n" +
    prefixLite(lite)
  );
}

export function writeAirAssets(): string[] {
  const changed: string[] = [];
  if (writeText(path.join(AIR_DIR, "theme.css"), buildThemeCss())) changed.push("kit/air/theme.css");
  if (writeText(path.join(AIR_DIR, "shell.css"), buildShellCss())) changed.push("kit/air/shell.css");
  fs.mkdirSync(path.join(AIR_DIR, "fonts"), { recursive: true });
  for (const f of fs.readdirSync(FONTS_SRC).sort()) {
    const src = fs.readFileSync(path.join(FONTS_SRC, f));
    const dest = path.join(AIR_DIR, "fonts", f);
    if (!fs.existsSync(dest) || !fs.readFileSync(dest).equals(src)) {
      fs.writeFileSync(dest, src);
      changed.push(`kit/air/fonts/${f}`);
    }
  }
  return changed;
}
