/**
 * DESIGN.md, ref.md and create-agent.system.md generation. Pure functions of
 * (prompts/src, catalog, meta) so `harvest` reproduces them byte for byte.
 */
import fs from "node:fs";
import path from "node:path";
import type { ComponentSpec } from "./catalog.ts";
import type { Meta } from "./meta.ts";
import { BUDGETS, KIT_VERSION } from "./meta.ts";
import { PROMPTS_SRC } from "./paths.ts";
import { readText } from "./fsx.ts";
import { SOURCES } from "./sources.ts";

const GENERATED = (what: string) =>
  `<!-- GENERATED by packages/create-kit/scripts/harvest.ts — do not edit. Edit prompts/src/*, scripts/lib/catalog.ts or a component's ref.md source and re-run harvest. ${what} -->\n\n`;

function recipes(): string {
  const dir = path.join(PROMPTS_SRC, "recipes");
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => readText(path.join(dir, f)).trim())
    .join("\n\n");
}

function kb(n: number): string {
  return n < 10 ? `${n.toFixed(1)}kb` : `${Math.round(n)}kb`;
}

export function catalogLine(meta: Meta, pathPrefix = "kit/"): string {
  const tags = meta.tags.join(", ");
  const weight = kb(meta.weightKb.js + meta.weightKb.css);
  return `<${meta.id} path="${pathPrefix}${meta.id}/ref.md" lite="${meta.lite}" weight="${weight}" tier="${meta.license.tier}" touch="${meta.touch}" motion="${meta.reducedMotion}">${meta.title} — ${meta.when} Tags: ${tags}</${meta.id}>`;
}

const GROUPS: readonly { readonly title: string; readonly match: (m: Meta) => boolean }[] = [
  { title: "Air shell and hooks", match: (m) => m.id.startsWith("air/") },
  { title: "Text and typography", match: (m) => m.tags.includes("text") },
  { title: "Status, thinking, streaming", match: (m) => ["status", "thinking", "streaming", "loading"].some((t) => m.tags.includes(t)) },
  { title: "Inputs and actions", match: (m) => ["input", "button", "approval", "composer", "action", "search"].some((t) => m.tags.includes(t)) },
  { title: "Lists, tables, cards", match: (m) => ["list", "table", "card", "chip", "pill", "data"].some((t) => m.tags.includes(t)) },
  { title: "Layout, media, motion blocks", match: (m) => ["layout", "media", "carousel", "gallery", "marquee", "scroll", "ambient"].some((t) => m.tags.includes(t)) },
  { title: "Filters, backgrounds, materials", match: (m) => ["filter", "background", "style", "material", "webgl"].some((t) => m.tags.includes(t)) },
  { title: "Foundations and helpers", match: () => true },
];

function catalogIndex(metas: readonly Meta[]): string {
  const seen = new Set<string>();
  const sections: string[] = [];
  for (const g of GROUPS) {
    const rows = metas.filter((m) => !seen.has(m.id) && g.match(m));
    if (rows.length === 0) continue;
    for (const m of rows) seen.add(m.id);
    sections.push(`### ${g.title}\n\n<components>\n${rows.map((m) => catalogLine(m)).join("\n")}\n</components>`);
  }
  return sections.join("\n\n");
}

function sourcesTable(): string {
  const rows = SOURCES.map(
    (s) => `| \`${s.id}\` | ${s.name} (${s.homepage}) | ${s.spdx} | ${s.tier} | ${s.pin.kind === "github" ? `${s.pin.repo}@${s.pin.commit.slice(0, 12)}` : `captured ${s.pin.captured}`} |`
  );
  return ["| Source | Name | License | Tier | Pin |", "| --- | --- | --- | --- | --- |", ...rows].join("\n");
}

function budgetsSection(liteJsKb: number, liteCssKb: number, metas: readonly Meta[]): string {
  const body = readText(path.join(PROMPTS_SRC, "budgets.md")).trim();
  const bundled = metas.filter((m) => m.lite && m.kind !== "helper").length;
  return `${body}\n\nMeasured for Kit ${KIT_VERSION}: the \`lite\` set (${bundled} renderable components, bundled together with React) is ${liteJsKb.toFixed(1)} KiB JS and ${liteCssKb.toFixed(1)} KiB CSS gzipped against budgets of ${BUDGETS.liteJsKb} KiB and ${BUDGETS.cssKb} KiB.`;
}

export interface DesignInputs {
  readonly metas: readonly Meta[];
  readonly liteJsKb: number;
  readonly liteCssKb: number;
}

export function buildDesign(inputs: DesignInputs): string {
  const liteCount = inputs.metas.filter((m) => m.lite).length;
  const parts = [
    GENERATED("Design doc (goal-create-v11 §12.3)."),
    `# Air Create — Design doc (Kit ${KIT_VERSION})\n\nRead top to bottom once, then open \`ref.md\` only for the components you pick. ${inputs.metas.length} components; ${liteCount} are \`lite\`.\n`,
    readText(path.join(PROMPTS_SRC, "doctrine.md")).trim(),
    `## 2. Recipes\n\nEight shapes cover almost every request. Start from the closest one and remove, never add, motion.\n\n${recipes()}`,
    `## 3. Catalog\n\nOne line per component: \`path\` is the reference to open, \`lite\` whether it may be used on a lite surface, \`weight\` gzipped KiB it adds (JS+CSS, own code), \`tier\` the license tier (only A ships in source), \`touch\` whether it works without hover, \`motion\` what happens under \`prefers-reduced-motion\` (static: a complete still frame; reduced: shorter; none: no motion to begin with; n/a: not animated).\n\n${catalogIndex(inputs.metas)}\n\n### Sources\n\n${sourcesTable()}`,
    readText(path.join(PROMPTS_SRC, "exclusions.md")).trim(),
    budgetsSection(inputs.liteJsKb, inputs.liteCssKb, inputs.metas),
  ];
  return parts.join("\n\n") + "\n";
}

export function buildSystemPrompt(inputs: DesignInputs): string {
  const liteMetas = inputs.metas.filter((m) => m.lite);
  const index = inputs.metas.map((m) => catalogLine(m, "~/.hermes/skills/create-miniapp/kit/")).join("\n");
  return (
    GENERATED("System prompt for Create sessions (goal-create-v11 §9.5, §12.5).") +
    readText(path.join(PROMPTS_SRC, "system.md")).trim() +
    "\n\n" +
    readText(path.join(PROMPTS_SRC, "doctrine.md")).trim() +
    `\n\n## Catalog index\n\n${inputs.metas.length} components, ${liteMetas.length} lite. Open \`path\` for what you pick.\n\n<components>\n${index}\n</components>\n\n` +
    readText(path.join(PROMPTS_SRC, "exclusions.md")).trim() +
    "\n\n" +
    budgetsSection(inputs.liteJsKb, inputs.liteCssKb, inputs.metas) +
    "\n"
  );
}

/**
 * The Box skill (goal-create-v11 §9.5). Frontmatter matches the other
 * template skills; the body is prompts/src/skill.md verbatim plus a Kit
 * stamp, so the skill and the system prompt share one source.
 */
export function buildSkill(inputs: DesignInputs): string {
  const liteCount = inputs.metas.filter((m) => m.lite).length;
  const frontmatter = [
    "---",
    "name: create-miniapp",
    'description: "Build or host a wzrd.tech mini-app for your human: a sentence (Vibe) or an HTML file / zip / folder (Drop) becomes a DRAFT at mini.wzrd.tech/<username>/<app-name>. You plan, build, QA and stage; only the owner makes it live."',
    "version: 2.0.0",
    "author: air",
    "license: MIT",
    "platforms: [linux]",
    "metadata:",
    "  hermes:",
    "    tags: [Apps, Create, Mini-Apps, Vibe, Approval]",
    "---",
  ].join("\n");
  return (
    frontmatter +
    "\n\n" +
    GENERATED("Box skill body (goal-create-v11 §9.5).") +
    readText(path.join(PROMPTS_SRC, "skill.md")).trim() +
    `\n\n---\n\nKit ${KIT_VERSION}: ${inputs.metas.length} components, ${liteCount} lite. DESIGN.md beside this file is the catalog.\n`
  );
}

function propsTable(props: Readonly<Record<string, string>>): string {
  const keys = Object.keys(props);
  if (keys.length === 0) return "_No props beyond `className`/`children`._";
  return ["| Prop | Type |", "| --- | --- |", ...keys.map((k) => `| \`${k}\` | \`${props[k]!.replace(/\|/g, "\\|")}\` |`)].join("\n");
}

function componentName(spec: ComponentSpec): string {
  if (spec.demoExport) return spec.demoExport;
  return spec.title.replace(/[^A-Za-z0-9]+/g, " ").trim().split(" ").map((w) => w[0]!.toUpperCase() + w.slice(1)).join("");
}

export function buildRef(spec: ComponentSpec, meta: Meta): string {
  const name = componentName(spec);
  const importPath = `./kit/${spec.id}`;
  const usage = spec.usage ?? `<${name}${Object.keys(meta.props).slice(0, 3).map((p) => ` ${p}={…}`).join("")} />`;
  const failure: string[] = [...(spec.notes ?? [])];
  if (!meta.touch) failure.push("Hover/pointer-driven: provide the same information without the interaction on touch.");
  if (!meta.lite) failure.push(`Not lite${meta.liteReason ? ` (${meta.liteReason})` : ""}: render a static fallback when \`useLite()\` is true.`);
  if (meta.reducedMotion === "static") failure.push("Under `prefers-reduced-motion` the final frame renders immediately; make sure that frame is complete.");
  if (meta.deps.includes("motion")) failure.push("Pulls `motion` (shared with other motion components; counted once per app).");
  const tokens =
    spec.source === "beautiful"
      ? "Beautiful UI tokens are bridged in `kit/beautiful/foundation/foundation.css`: `--page`→`--canvas`, `--surface`→`--panel-bg`, `--inset`→`--well-bg`, `--ink-2`→`--ink-muted`, `--line`→`--ring`, `--accent-ink`→`--accent`. Import `kit/beautiful/foundation` once per app."
      : spec.source === "aicss"
        ? "AI CSS components read `--background`, `--foreground`, `--muted`, `--border`, `--primary` via the `@theme inline` bridge in `kit/air/theme.css`; no per-component mapping needed."
        : "Colours, radii and fonts come from `kit/air/theme.css` custom properties (`--ink`, `--accent`, `--panel-bg`, `--ring`, `--radius-*`, `--font-*`); pass them through `className`/`style`, never literals.";
  return (
    GENERATED(`Reference for ${spec.id}.`) +
    `# ${meta.title} (\`${meta.id}\`)\n\n` +
    `${meta.when}\n\n` +
    `- **Weight**: ${meta.weightKb.js} KiB JS + ${meta.weightKb.css} KiB CSS (own, gzip); ${meta.weightKb.jsFull} KiB with vendor deps. **Lite**: ${meta.lite}. **Touch**: ${meta.touch}. **Reduced motion**: ${meta.reducedMotion}.\n` +
    `- **License**: ${meta.license.spdx}, tier ${meta.license.tier}, from \`${meta.license.source}\`${meta.author ? ` by ${meta.author}` : ""}.\n` +
    `- **Deps**: ${meta.deps.length ? meta.deps.map((d) => `\`${d}\``).join(", ") : "none beyond React"}.\n\n` +
    `## Usage\n\n\`\`\`tsx\nimport ${spec.kind === "style" ? `"${importPath}"` : `{ ${name} } from "${importPath}"`};\n\n${usage}\n\`\`\`\n\n` +
    `## Props\n\n${propsTable(meta.props)}\n\n` +
    `## Compose\n\n1. Inside a shell \`.panel\` as the screen's one hero element, with the headline in \`--font-body\` and labels in \`.kicker\`.\n2. As a row in a list/card (\`.item\`, \`.card\`) where it is decoration for the text next to it — then it must be \`aria-hidden\`.\n\n` +
    `## Failure modes\n\n${failure.length ? failure.map((f) => `- ${f}`).join("\n") : "- None recorded."}\n\n` +
    `## Air tokens\n\n${tokens}\n`
  );
}
